# Generated by Django 4.2.16 on 2024-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.IntegerField(choices=[(0, 'any'), (1, 'meat'), (2, 'fish'), (3, 'veg'), (4, 'fruit'), (5, 'dairy'), (6, 'eggs'), (7, 'bread'), (8, 'grains')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(related_name='posts', to='blog.ingredient'),
        ),
    ]
