# Generated by Django 4.2.16 on 2024-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ingredient_post_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'any'), (1, 'starter'), (2, 'main'), (3, 'pudding'), (4, 'snack'), (5, 'sweet_treat'), (6, 'portable'), (7, 'entertaining'), (8, 'healthy')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='select_posts', to='blog.category'),
        ),
    ]
