# Generated by Django 4.2.16 on 2024-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.IntegerField(choices=[(0, 'any'), (1, 'starter'), (2, 'main'), (3, 'pudding'), (4, 'snack'), (5, 'sweet_treat'), (6, 'portable'), (7, 'entertaining'), (8, 'healthy'), (9, 'breakfast'), (10, 'lunch'), (11, 'dinner')], default=0),
        ),
    ]
