# Generated by Django 4.2.16 on 2024-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_thumbsup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbsup',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='posts', to='blog.like'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='fk_post_id',
        ),
    ]
