# Generated by Django 4.2.16 on 2024-12-09 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_post_alt_image_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='fk_post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='alt_image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('fk_post_id', 'fk_user_id')},
        ),
    ]
