# Generated by Django 4.2.16 on 2024-12-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_likes_like_fk_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.IntegerField(choices=[(0, 'any'), (1, 'meat'), (2, 'fish'), (3, 'veg'), (4, 'fruit'), (5, 'dairy'), (6, 'eggs'), (7, 'bread'), (8, 'grains'), (9, 'seasonal')], default=0),
        ),
    ]
